trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest
stages:
- stage: SwaDEV
  displayName: Static Web Apps DEV

  jobs:
  - deployment: dev_deploy
    #pool:
    #  vmImage: $(vmImageName) 
    displayName: Deploy en Dev
    environment: 'DEV_SWA'
    variables:
      - name: environment
        value: DEV
      - group: ${{ format('variables-{0}', variables.environment) }}  
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls -lh
            displayName: 'Listandoo en Build' 
          - task: AzureStaticWebApp@0
            inputs:
             app_location: '/static-app/Client' # App source code path
             api_location: '/static-app/Api' # Api source code path - optional
             output_location: 'wwwroot' # Built app content directory - optional
             azure_static_web_apps_api_token: $(swa_deployment_token)
        
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy  #not a job... a deployment!
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"
            displayName: 'Msg Deploy QA'
